import { JetBrains_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./styles/global.scss";
import styles from "./styles.module.scss";

// If loading a variable font, you don't need to specify the font weight
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Kayo Kalinauskas",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jetbrains.variable} ${poppins.variable}`}>
      <body className={styles.body}>{children}</body>
    </html>
  );
}
