import { JetBrains_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "../styles/global.scss";
import styles from "../styles.module.scss";
import i18nConfig from "../../i18nConfig.js";
import { Suspense } from "react";
import Loading from "./loading";

let locales = ["en-US", "pt-BR"];

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Kayo Kalinauskas",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} className={`${jetbrains.variable} ${poppins.variable}`}>
      <body className={styles.body}>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
